export default {
  maxWidth: 1256,
  breakpoints: [48, 62, 78.5],
  space: [0, 5, 10, 15, 25, 50],
  defaultFontSize: 16,
  fontSizes: [10, 12, 14, 16, 18, 24, 30, 48, 64],
  border: "1px solid #f0f0f0",
  colors: {
    black: "#000",
    default: "#333",
    secondary: "#666",
    gray: "#666",
    lightGray: "#999",
    grayDark: "#ccc",
    white: "#fff",
    blue: "#39c",
    pink: "#f09",
    green: "#77c054",
    borderDark: "#ccc",
    borderMedium: "#f0f0f0",
    borderLight: "#eee",
    borderBlue: "#00aeef",
    background: "#f1f1f1",
    backgroundGray: "#f3f3f3",
    backgroundMediumGray: "#dcdcdc",
    red: "#ef542c",
    headerBackground: "#ffffff",
    footerBackground: "#e9e9e9",
    browseBackground: "#f1f1f1",
  },
  fontFamilySerif: "Crimson Text, serif",
  fontFamilySans: "Helvetica, sans-serif",
  fontFamilyMonospace:
    "Menlo, Bitstream Vera Sans, Monaco, Andale Mono, Lucida Console, Droid Mono, monospace",
  borderRadius: 4,
}
